class JOSEError(Exception): ...
class JWSError(JOSEError): ...
class JWSSignatureError(JWSError): ...
class JWSAlgorithmError(JWSError): ...
class JWTError(JOSEError): ...
class JWTClaimsError(JWTError): ...
class ExpiredSignatureError(JWTError): ...
class JWKError(JOSEError): ...

class JWEError(JOSEError):
    """Base error for all JWE errors"""

class JWEParseError(JWEError):
    """Could not parse the JWE string provided"""

class JWEInvalidAuth(JWEError):
    """
    The authentication tag did not match the protected sections of the
    JWE string provided
    """

class JWEAlgorithmUnsupportedError(JWEError):
    """
    The JWE algorithm is not supported by the backend
    """
