from typing import Final

from .segment import Segment

MUTATION_UNSUPPORTED_MESSAGE: Final[str]

class FacadeSegment(Segment):
    """
    This type of segment should only be used in an AWS Lambda environment.
    It holds the same id, traceid and sampling decision as
    the segment generated by Lambda service but its properties cannot
    be mutated except for its subsegments. If this segment is created
    before Lambda worker finishes initializatioin, all the child
    subsegments will be discarded.
    """

    initializing: bool
    def __init__(self, name: str, entityid: str | None, traceid: str | None, sampled: bool | None) -> None: ...
