import collections.abc  # noqa: F401
import typing_extensions  # noqa: F401

class object: ...
class type: ...
class function: ...
class ellipsis: ...
class BaseException: ...
class int: ...
class str: ...
class slice: ...
class list: ...
class tuple: ...
class dict: ...

Ellipsis: ellipsis
