from collections.abc import Iterator
from typing import Any, MutableMapping, MutableSequence, Sequence, TypeVar, overload  # noqa: Y022
from typing_extensions import Literal, TypeAlias

SupportsRichComparison = Any
SupportsRichComparisonT = Any

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

class object: ...
class staticmethod: ...
class classmethod: ...
class type: ...
class function: ...
class property: ...
class ellipsis: ...
class BaseException: ...
class int: ...
class float: ...
class bytes(Sequence[int]): ...
class bool(int): ...
class slice: ...
class str(Sequence[str]): ...
class list(MutableSequence[_T]): ...

_PositiveInteger: TypeAlias = Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
_NegativeInteger: TypeAlias = Literal[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20]
_LiteralInteger = _PositiveInteger | _NegativeInteger | Literal[0]  # noqa: Y026  # TODO: Use TypeAlias once mypy bugs are fixed

class tuple(Sequence[_T_co]):
    def __len__(self) -> int: ...
    def __contains__(self, __key: object) -> bool: ...
    @overload
    def __getitem__(self, __key: int) -> _T_co: ...
    @overload
    def __getitem__(self, __key: slice) -> tuple[_T_co, ...]: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def __lt__(self, __value: tuple[_T_co, ...]) -> bool: ...
    def __le__(self, __value: tuple[_T_co, ...]) -> bool: ...
    def __gt__(self, __value: tuple[_T_co, ...]) -> bool: ...
    def __ge__(self, __value: tuple[_T_co, ...]) -> bool: ...
    def __eq__(self, __value: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __mul__(self, __value: int) -> tuple[_T_co, ...]: ...
    def __rmul__(self, __value: int) -> tuple[_T_co, ...]: ...
    def count(self, __value: Any) -> int: ...
    def index(self, __value: Any, __start: int = 0, __stop: int = ...) -> int: ...

class dict(MutableMapping[_KT, _VT]): ...

Ellipsis: ellipsis
