import zipfile
from _typeshed import Incomplete, StrPath
from io import BufferedReader
from typing import NoReturn
from typing_extensions import Literal, Never

class FileReader:
    def __init__(self, loader) -> None: ...
    def resource_path(self, resource: StrPath) -> str: ...

class ZipReader:
    prefix: str
    archive: Incomplete
    def __init__(self, loader, module: str) -> None: ...
    def open_resource(self, resource: str) -> BufferedReader: ...
    def is_resource(self, path: StrPath) -> bool: ...
    def files(self) -> zipfile.Path: ...

class MultiplexedPath:
    def read_bytes(self) -> NoReturn: ...
    def read_text(self, *args: Never, **kwargs: Never) -> NoReturn: ...  # type: ignore[override]
    def is_dir(self) -> Literal[True]: ...
    def is_file(self) -> Literal[False]: ...
    def open(self, *args: Never, **kwargs: Never) -> NoReturn: ...  # type: ignore[override]
    @property
    def name(self) -> str: ...

class NamespaceReader:
    path: MultiplexedPath
    def __init__(self, namespace_path) -> None: ...
    def resource_path(self, resource: str) -> str: ...
    def files(self) -> MultiplexedPath: ...
