version = "68.2.*"
upstream_repository = "https://github.com/pypa/setuptools"
partial_stub = true
obsolete_since = "69.0.0" # Released on 2023-11-20

[tool.stubtest]
# darwin is equivalent to linux for OS-specific methods
platforms = ["linux", "win32"]
