import codecs
from _typeshed import Incomplete

class Codec(codecs.Codec):
    encode: Incomplete
    decode: Incomplete

class IncrementalEncoder(codecs.IncrementalEncoder):
    mapping: Incomplete
    def __init__(self, errors: str = ..., mapping: Incomplete | None = ...) -> None: ...
    def encode(self, input, final: bool = ...): ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    mapping: Incomplete
    def __init__(self, errors: str = ..., mapping: Incomplete | None = ...) -> None: ...
    def decode(self, input, final: bool = ...): ...

class StreamWriter(Codec, codecs.StreamWriter):
    mapping: Incomplete
    def __init__(self, stream, errors: str = ..., mapping: Incomplete | None = ...) -> None: ...
    def encode(self, input, errors: str = ...): ...

class StreamReader(Codec, codecs.StreamReader):
    mapping: Incomplete
    def __init__(self, stream, errors: str = ..., mapping: Incomplete | None = ...) -> None: ...
    def decode(self, input, errors: str = ...): ...

def getregentry(): ...
