import codecs
from _typeshed import Incomplete

class Codec(codecs.Codec):
    def encode(self, input, errors: str = ...): ...
    def decode(self, input, errors: str = ...): ...

class IncrementalEncoder(codecs.IncrementalEncoder):
    def encode(self, input, final: bool = ...): ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, input, final: bool = ...): ...

class StreamWriter(Codec, codecs.StreamWriter): ...
class StreamReader(Codec, codecs.StreamReader): ...

def getregentry(): ...

decoding_map: Incomplete
decoding_table: str
encoding_map: Incomplete
