import codecs

def quopri_encode(input, errors: str = "strict"): ...
def quopri_decode(input, errors: str = "strict"): ...

class Codec(codecs.Codec):
    def encode(self, input, errors: str = "strict"): ...
    def decode(self, input, errors: str = "strict"): ...

class IncrementalEncoder(codecs.IncrementalEncoder):
    def encode(self, input: str, final: bool = False) -> bytes: ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, input, final: bool = False) -> str: ...

class StreamWriter(Codec, codecs.StreamWriter):
    charbuffertype = bytes

class StreamReader(Codec, codecs.StreamReader):
    charbuffertype = bytes

def getregentry() -> codecs.CodecInfo: ...
