import codecs
from _typeshed import Incomplete

class Codec(codecs.Codec):
    def encode(self, input, errors: str = "strict"): ...
    def decode(self, input, errors: str = "strict"): ...

class IncrementalEncoder(codecs.IncrementalEncoder):
    def encode(self, input: str, final: bool = False) -> bytes: ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, input, final: bool = False) -> str: ...

class StreamWriter(Codec, codecs.StreamWriter): ...
class StreamReader(Codec, codecs.StreamReader): ...

def getregentry() -> codecs.CodecInfo: ...

rot13_map: Incomplete

def rot13(infile, outfile) -> None: ...
