import codecs

class Codec(codecs.Codec):
    def encode(self, input, errors: str = ...) -> None: ...
    def decode(self, input, errors: str = ...) -> None: ...

class IncrementalEncoder(codecs.IncrementalEncoder):
    def encode(self, input, final: bool = ...) -> None: ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, input, final: bool = ...) -> None: ...

class StreamWriter(Codec, codecs.StreamWriter): ...
class StreamReader(Codec, codecs.StreamReader): ...

def getregentry(): ...
