"""passlib.crypto._blowfish._gen_files - meta script that generates unrolled.py"""

from typing import Any

def varlist(name, count): ...
def indent_block(block, padding):
    """ident block of text"""

BFSTR: Any

def render_encipher(write, indent: int = 0) -> None: ...
def write_encipher_function(write, indent: int = 0) -> None: ...
def write_expand_function(write, indent: int = 0) -> None: ...
def main() -> None: ...
