"""passlib.crypto._blowfish.unrolled - unrolled loop implementation of bcrypt,
autogenerated by _gen_files.py

currently this override the encipher() and expand() methods
with optimized versions, and leaves the other base.py methods alone.
"""

from passlib.crypto._blowfish.base import BlowfishEngine as _BlowfishEngine

class BlowfishEngine(_BlowfishEngine):
    def encipher(self, l, r):
        """blowfish encipher a single 64-bit block encoded as two 32-bit ints"""

    def expand(self, key_words) -> None:
        """unrolled version of blowfish key expansion"""

__all__ = ["BlowfishEngine"]
