name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "scripts/**"

permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pyright:
    name: "pyright: Run test cases"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v7
        with:
          version-file: "requirements-tests.txt"
      - name: Install typeshed test-suite requirements
        # Install these so we can run `get_*_requirements.py`
        run: uv pip install -r requirements-tests.txt --system
      - name: Install required APT packages
        run: |
          PACKAGES=$(python tests/get_stubtest_system_requirements.py)
          if [ -n "$PACKAGES" ]; then
            printf "Installing APT packages:\n  $(echo $PACKAGES | sed 's/ /\n  /g')\n"
            sudo apt-get update -q && sudo apt-get install -qy $PACKAGES
          fi
      - name: Create an isolated venv for testing
        run: uv venv .venv
      - name: Install 3rd-party stub dependencies
        run: |
          PACKAGES=$(python tests/get_external_stub_requirements.py)
          if [ -n "$PACKAGES" ]; then
              printf "Installing python packages:\n  $(echo $PACKAGES | sed 's/ /\n  /g')\n"
              uv pip install --python-version 3.13 $PACKAGES
          fi
      - name: Activate the isolated venv for the rest of the job
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: List 3rd-party stub dependencies installed
        run: uv pip freeze
      - name: Run pyright on the test cases
        uses: jakebailey/pyright-action@v2
        with:
          version: PATH
          python-platform: 'Linux'
          python-version: '3.13'
          annotate: true
          project: ./pyrightconfig.testcases.json
